name: notebook-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from master
        uses: actions/checkout@v2
      - name: Install node 12.18.2
        uses: actions/setup-node@v2
        with:
          node-version: 12.18.2
      - name: Install gitbook tools
        run: npm install gitbook-cli gitbook-summary -g
      - name: Set timezone to shanghai
        run: sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - name: Exec gitbook install
        run: gitbook install
      - name: Clear README.md file
        run: echo "" > README.md
      - name: Exec book sm
        run: book sm --disableTitleFormatting
      - name: Exec gitbook build
        run: gitbook build . /tmp/docs
      - name: Install git tools
        run: sudo apt-get install git -y
      - name: Build notebook and publish
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd /tmp/docs
          git init
          git config --global user.name "Zhenhai Gao"
          git config --global user.email "gaozh1988@live.com"
          git remote add origin "https://github.com/gaozhenhai/notebook.git"
          git add .
          git commit -m "update notebooks from ci"
          git push --force "https://$ACCESS_TOKEN@github.com/gaozhenhai/notebook" master:docs
